version: '3'

services:
  app:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    restart: on-failure
    depends_on:
      - fastapi_udemy_db
    ports:
     - "8000:8000"
    networks:
      - fastapi-network

  db:
    image: postgres
    container_name: fastapi_udemy_db
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    volumes:
        - pgdata:/var/lib/postgresql/data/
    ports:
      - "5417:5432"
    networks:
      - fastapi-network


networks:
  fastapi-network:

volumes:
  pgdata: